### ISSUE TITLE
"IOError: [Errno 2] No such file or directory" creating environment.

### ISSUE THREAD

**Issue by mjscosta** [JetBrains/gradle-python-envs#16]
Issuing command `gradle build_envs`:

Initial bootstrap, miniconda gets installed, after that the environment I've defined in the build.gradle crashes. With the error:

`    IOError: [Errno 2] No such file or directory: u'/vagrant/project-test1/build/bootstrap/miniconda_latest_64/pkgs/openssl-1.0.2l-0/info/index.json'`

Build script

```
plugins {
  id "com.jetbrains.python.envs" version "0.0.18"
}

envs {
  bootstrapDirectory = new File(buildDir, 'bootstrap')
  envsDirectory = new File(buildDir, 'envs')
    conda "project-test1", "3.5", "64", ["pycodestyle==2.3.1", "pylint==1.7.2", "pytest-cov==2.5.1"     ]
}

task coverage() {
    doLast() {
        println 'coverage task'
    }
}
```

See full log:

```> Task :Bootstrap MINICONDA 64 bit
Bootstraping to /vagrant/project-test1/build/bootstrap/miniconda_latest_64
PREFIX=/vagrant/project-test1/build/bootstrap/miniconda_latest_64
installing: python-2.7.13-0 ...
installing: asn1crypto-0.22.0-py27_0 ...
installing: cffi-1.10.0-py27_0 ...
installing: conda-env-2.6.0-0 ...
installing: cryptography-1.8.1-py27_0 ...
installing: enum34-1.1.6-py27_0 ...
installing: idna-2.5-py27_0 ...
installing: ipaddress-1.0.18-py27_0 ...
installing: libffi-3.2.1-1 ...
installing: openssl-1.0.2l-0 ...
installing: packaging-16.8-py27_0 ...
installing: pycosat-0.6.2-py27_0 ...
installing: pycparser-2.17-py27_0 ...
installing: pyopenssl-17.0.0-py27_0 ...
installing: pyparsing-2.1.4-py27_0 ...
installing: readline-6.2-2 ...
installing: requests-2.14.2-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_1 ...
installing: setuptools-27.2.0-py27_0 ...
installing: six-1.10.0-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.3.21-py27_0 ...
installing: pip-9.0.1-py27_1 ...
installing: wheel-0.29.0-py27_0 ...
Python 2.7.13 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Installing packages via conda: []

> Task :Create conda env 'project-test1'
Creating condaenv 'project-test1' at /vagrant/project-test1/build/envs/project-test1 directory
Fetching package metadata .........
Solving package specifications: . 0s]

Package plan for installation in environment /vagrant/project-test1/build/envs/project-test1:

The following NEW packages will be INSTALLED:

    certifi:    2016.2.28-py35_0
    openssl:    1.0.2l-0        
    pip:        9.0.1-py35_1    
    python:     3.5.4-0         
    readline:   6.2-2           
    setuptools: 36.4.0-py35_1   
    sqlite:     3.13.0-0        
    tk:         8.5.18-0        
    wheel:      0.29.0-py35_0   
    xz:         5.2.3-0         
    zlib:       1.2.11-0        

openssl-1.0.2l  64% |####################           | ETA:  0:00:01   1.02 MB/s                                                                                                                openssl-1.0.2l 100% |###############################| Time: 0:00:05 635.30 kB/s
readline-6.2-2  66% |####################           | Time: 0:00:00   2.37 MB/s                                                                                                               lreadline-6.2-2 100% |###############################| Time: 0:00:00   2.53 MB/s
sqlite-3.13.0-  14% |####                           | Time: 0:00:00   2.31 MB/s                                                                                                                sqlite-3.13.0-  34% |##########                     | Time: 0:00:00   2.76 MB/s                                                                                                                sqlite-3.13.0-  54% |################               | Time: 0:00:00   2.94 MB/s                                                                                                                sqlite-3.13.0-  74% |#######################        | Time: 0:00:01   3.06 MB/s                                                                                                                sqlite-3.13.0-  94% |#############################  | Time: 0:00:01   3.11 MB/s                                                                                                               isqlite-3.13.0- 100% |###############################| Time: 0:00:01   3.10 MB/s
tk-8.5.18-0.ta  30% |#########                      | Time: 0:00:00   3.37 MB/s                                                                                                               %tk-8.5.18-0.ta  72% |######################         | Time: 0:00:00   3.31 MB/s                                                                                                               #tk-8.5.18-0.ta 100% |###############################| Time: 0:00:00   3.25 MB/s
xz-5.2.3-0.tar  38% |###########                    | Time: 0:00:00   2.53 MB/s                                                                                                                xz-5.2.3-0.tar 100% |###############################| Time: 0:00:00   1.83 MB/s
zlib-1.2.11-0. 100% |###############################| Time: 0:00:00   2.14 MB/s
python-3.5.4-0   1% |                               | Time: 0:00:00   2.46 MB/s                                                                                                               0python-3.5.4-0  11% |###                            | Time: 0:00:00   2.92 MB/s                                                                                                                python-3.5.4-0  16% |#####                          | Time: 0:00:00   2.84 MB/s                                                                                                                python-3.5.4-0  21% |######                         | Time: 0:00:01   2.81 MB/s                                                                                                                python-3.5.4-0  26% |########                       | Time: 0:00:01   2.73 MB/s                                                                                                               0python-3.5.4-0  36% |###########                    | Time: 0:00:02   2.78 MB/s                                                                                                                python-3.5.4-0  41% |############                   | Time: 0:00:02   2.82 MB/s                                                                                                               #python-3.5.4-0  46% |##############                 | Time: 0:00:02   2.84 MB/s                                                                                                                python-3.5.4-0  51% |###############                | Time: 0:00:02   2.87 MB/s                                                                                                               0python-3.5.4-0  61% |###################            | Time: 0:00:03   2.92 MB/s                                                                                                                python-3.5.4-0  66% |####################           | Time: 0:00:03   2.94 MB/s                                                                                                               #python-3.5.4-0  71% |######################         | Time: 0:00:04   2.93 MB/s                                                                                                                python-3.5.4-0  76% |#######################        | Time: 0:00:04   2.94 MB/s                                                                                                               0python-3.5.4-0  86% |##########################     | Time: 0:00:05   2.82 MB/s                                                                                                                python-3.5.4-0  91% |############################   | Time: 0:00:05   2.73 MB/s                                                                                                               #python-3.5.4-0  96% |#############################  | Time: 0:00:05   2.74 MB/s                                                                                                               #python-3.5.4-0 100% |###############################| Time: 0:00:06   2.75 MB/s
certifi-2016.2 100% |###############################| Time: 0:00:00   2.79 MB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00   2.63 MB/s
setuptools-36. 100% |###############################| Time: 0:00:00   3.23 MB/s
pip-9.0.1-py35   4% |#                              | Time: 0:00:00   2.80 MB/s                                                                                                               Mpip-9.0.1-py35  50% |###############                | Time: 0:00:00   3.26 MB/s                                                                                                               ypip-9.0.1-py35  97% |#############################  | Time: 0:00:00   3.25 MB/s                                                                                                               An unexpected error has occurred.m 31s]
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /vagrant/project-test1/build/bootstrap/miniconda_latest_64  (writable)
    default environment : /vagrant/project-test1/build/bootstrap/miniconda_latest_64
       envs directories : /vagrant/project-test1/build/bootstrap/miniconda_latest_64/envs
                          /home/vagrant/.conda/envs
          package cache : /vagrant/project-test1/build/bootstrap/miniconda_latest_64/pkgs
                          /home/vagrant/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Linux/4.4.0-31-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /vagrant/project-test1/build/bootstrap/miniconda_latest_64/bin/conda create -p /vagrant/project-test1/build/envs/project-test1 -y python=3.5`




    Traceback (most recent call last):
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/core/link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/core/link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 81, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/vagrant/project-test1/build/bootstrap/miniconda_latest_64/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 100, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'/vagrant/project-test1/build/bootstrap/miniconda_latest_64/pkgs/openssl-1.0.2l-0/info/index.json'

pip-9.0.1-py35 100% |###############################| Time: 0:00:00   3.25 MB/s


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Create conda env 'project-test1''.
> Process 'command '/vagrant/project-test1/build/bootstrap/miniconda_latest_64/bin/conda'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
2 actionable tasks: 2 executed
```

**Comment by ARostovsky** [comment]
Seems like conda issue, please check https://github.com/conda/conda-build/issues/3065
