### ISSUE TITLE
Execution failed for task ':install_python_build' due to java.io.FileNotFoundException (when running 'clean test')

### ISSUE THREAD

**Issue by gregoavg** [JetBrains/gradle-python-envs#26]
### Description: 
I've got a python sub-module on a project managed by gradle. The goal is to run python tests (via command: `python setup.py test`) on a python environment managed by the gradle-python-envs plugin.
This happens it 2 phases:
1) run the `build_envs` task
2) source the generated python virtual environment and run python command.

The corresponding build.gradle file that configures the above actions is on this gist: https://gist.github.com/gregoavg/c736105c8d715a8b5a3036b74907fd09

### When:
Running the tests from the project root via gradle wrapper with the following:
`./gradlew clean test`
Or even building the whole project (or directly the submodule) with:
`./gradlew clean test build`

### Expected:
Clean task should delete the `buildDir` and the `build_envs` task that is being invoked
via the test one, should recreate the build directory. 
This will allow the `install_python_build` to use the `buildDir` and download the pyenv sources.

### Result:
The `buildDir` directory get's deleted normally by the clean task. The `install_python_build` get's invoked and tries to create a file on the path of the build directory, that does not exist anymore.

The build fails with the following stacktrace:
```
Caused by: : java.io.FileNotFoundException: /path/to/build/pyenv.zip (No such file or directory)
        at org.apache.tools.ant.taskdefs.Get.execute(Get.java:151)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:103)
        at com.jetbrains.python.envs.PythonEnvsPlugin$_createInstallPythonBuildTask_closure2$_closure16$_closure17.doCall(PythonEnvsPlugin.groovy:81)
        at com.jetbrains.python.envs.PythonEnvsPlugin$_createInstallPythonBuildTask_closure2$_closure16.doCall(PythonEnvsPlugin.groovy:79)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 70 more
Caused by: java.io.FileNotFoundException: /path/to/build/pyenv.zip (No such file or directory)
        at org.apache.tools.ant.taskdefs.Get$GetThread.downloadFile(Get.java:815)
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:647)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:631)
```
The responsible line on the plugin in this:
https://github.com/JetBrains/gradle-python-envs/blob/6a4dfa5a867a3d086bb4910b53bcea89f288a621/src/main/groovy/com/jetbrains/python/envs/PythonEnvsPlugin.groovy#L79

## Proposed solution:
Ensure that the buildDir is present (if it's not, execute a command to create it), before the `doLast` closure of the task is being executed.
This could be added as a `doFirst` part of the task.

> **OFC, I will be more that happy to provide a PR with a proposed solution for this issue, if you consider this action as a helpful addition for the plugin needs.**

**Comment by Dexterp37** [comment]
@ARostovsky , hi! Is there any near-term plan for fixing this issue?

**Comment by gregoavg** [comment]
> @ARostovsky , hi! Is there any near-term plan for fixing this issue?
I've asked on this thread quite some time ago it they accept PR so I can issue one (the fix for this one is obvious), but had no response, IDK if this project is active on JetBrains side.

**Comment by ARostovsky** [comment]
@gregoavg @Dexterp37 
Hi, guys! Sorry for such late response.
I don't quite understand why do you want to delete buildDir instead of corresponding envDir in your clean tasks?
Every time you calling `build_envs`, buildDir should be re-created by this line
https://github.com/JetBrains/gradle-python-envs/blob/6a4dfa5a867a3d086bb4910b53bcea89f288a621/src/main/groovy/com/jetbrains/python/envs/PythonEnvsPlugin.groovy#L228

Probably this one isn't good enough and can be changed to project.mkdir(project.buildDir), but I still don't get what happens in your cases.

P.S. PRs are always welcome

**Comment by gregoavg** [comment]
Hi @ARostovsky and thank you for your reply.
Let me answer your questions one-by-one:
> I don't quite understand why do you want to delete buildDir instead of corresponding envDir in your clean tasks?

In this use-case, the corresponding envDir is under the module's build directory (ex. ```envsDirectory = file(buildDir)```). This is preferred due to the native simplicity that the gradle clean task provides (by definition it deletes the $buildDIr). Moreover, if your project is multi-moduled (like the one I'm using this plugin on), you can keep the actual python sources on the root buildDir and the corresponding venv to the target module buildDir.

> Every time you calling build_envs, buildDir should be re-created by this line
https://github.com/JetBrains/gradle-python-envs/blob/6a4dfa5a867a3d086bb4910b53bcea89f288a621/src/main/groovy/com/jetbrains/python/envs/PythonEnvsPlugin.groovy#L228

Well, this line seems to be executed during the gradle's configuration phase. Then, during the actual execution phase, the ```clean``` command removes the directory and the following task ```install_python_build``` invoked from ```build_envs``` cannot use the directory since it does not exist anymore. Adding that on a doFirst/doLast clause can solve this. Could you please verify that?

PS: Another thing regarding that line. The build directory is hardcoded. In cases that one is not targeting java sources, this directory can vary, since one can change it by overwriting the 'buildDir' property. Please, consider using ```"$buildDir"``` as path parameter to mkdir command.

**Comment by ARostovsky** [comment]
Guys, please test 0.0.26 (latest) version, this should be fixed.
