### ISSUE TITLE
Ambiguious call when no directory set

### ISSUE THREAD

**Issue by dotCipher** [JetBrains/gradle-python-envs#32]
Given a basic `build.gradle.kts` (using the kotlin-dsl):

```
plugins {
    base
    idea
    id("com.jetbrains.python.envs") version "0.0.30"
}

envs {
    python("python35_64", "3.7.2", "64", listOf())
}
```

Running `./gradlew tasks --stacktrace` gives the following error:
```
* What went wrong:
Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
        [class java.lang.String, class java.lang.String]
        [class java.io.File, class java.lang.String]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
        [class java.lang.String, class java.lang.String]
        [class java.io.File, class java.lang.String]
        at com.jetbrains.python.envs.Python.<init>(PythonEnvsExtension.groovy:231)
        at com.jetbrains.python.envs.Python.<init>(PythonEnvsExtension.groovy)
        at com.jetbrains.python.envs.PythonEnvsExtension.python(PythonEnvsExtension.groovy:41)
        at Build_gradle$2.execute(build.gradle.kts:40)
        at Build_gradle$2.execute(build.gradle.kts:3)
```

What I noticed is that when I change the `envs` block to include a `bootstrapDirectory`, I am able to successfully run `./gradlew tasks`, so it seems like this error has something to do with the null value being passed as the bootstrap dir?

**Comment by dotCipher** [comment]
Seems like this is the same problem when using `virtualenv()` and no `envsDirectory` is set.
